name: aquaria_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio:
  ionicons:
  rflutter_alert:
  provider:
  dropdown_button2: ^2.3.9
  image_picker: ^1.0.7
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  flutter_neumorphic_plus: ^3.3.0
  cached_network_image: ^3.3.1
  popup_banner: ^1.0.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
